CREATE TABLE KR_NASA_TABLE_SEQ
(
    TABLE_NAME      VARCHAR2(30),
    CURRENT_ID      NUMBER(38),
    PREVIOUS_ID     NUMBER(38),
    TOROKUYMD		VARCHAR2(8),
    TOROKUHMS		VARCHAR2(6),
    TOROKUUSER		VARCHAR2(50),
    KOSINYMD		VARCHAR2(8),
    KOSINHMS		VARCHAR2(6),
    KOSINUSER		VARCHAR2(50),
    BIKO			VARCHAR2(250)
)
;

ALTER TABLE KR_NASA_TABLE_SEQ ADD CONSTRAINT PK_KR_NASA_TABLE_SEQ PRIMARY KEY (TABLE_NAME)
;
