CREATE TABLE RS_SUBJECTID_XQLPATH_IDX (
	SUBJECT_ID				VARCHAR2(500),
	PATH					VARCHAR2(500),
	REVISION				NUMBER(38,0),
	COMMITER				VARCHAR2(60),
	UPDATE_FLG				CHAR(1)	DEFAULT '0' NOT NULL,
	NEW_FLG					CHAR(1)	DEFAULT '0' NOT NULL,
	FILE_NAME				VARCHAR2(500),
	TOROKUYMD				VARCHAR2(8),
	TOROKUHMS				VARCHAR2(6),
	TOROKUUSER				VARCHAR2(50),
	KOSINYMD				VARCHAR2(8),
	KOSINHMS				VARCHAR2(6),
	KOSINUSER				VARCHAR2(50),
	BIKO					VARCHAR2(250)
)
;

ALTER TABLE RS_SUBJECTID_XQLPATH_IDX ADD CONSTRAINT PK_RS_SUBJECTID_XQLPATH_IDX PRIMARY KEY  (SUBJECT_ID,PATH)
;
