CREATE TABLE  TR_COMMIT_HISTORY (
    REPOSITORY_KIND         VARCHAR2(30),
    REPOSITORY_NAME         VARCHAR2(30),
    ROOT_URL                VARCHAR2(300),
    RIGHT_BASE_URL          VARCHAR2(300),
    LEFT_BASE_URL           VARCHAR2(300),
	REVISION	            NUMBER(38,0),
	COMMITTER	            VARCHAR2(2000),
	COMMENTS	            VARCHAR2(2000),
	ACTION		            VARCHAR2(5),
	PATH		            VARCHAR2(2000),
	FILE_NAME	            VARCHAR2(2000),
	COMMIT_YMD	            VARCHAR2(8),
	COMMIT_HMS		        VARCHAR2(6),
	TOROKUYMD				VARCHAR2(8),
	TOROKUHMS				VARCHAR2(6),
	TOROKUUSER				VARCHAR2(50),
	KOSINYMD				VARCHAR2(8),
	KOSINHMS				VARCHAR2(6),
	KOSINUSER				VARCHAR2(50),
	BIKO					VARCHAR2(250)
)
;

ALTER TABLE TR_COMMIT_HISTORY ADD CONSTRAINT PK_TR_COMMIT_HISTORY PRIMARY KEY
(REPOSITORY_NAME,ROOT_URL,RIGHT_BASE_URL,LEFT_BASE_URL,PATH);
