INSERT INTO RR_ERD_RELEASES RR(
    AF_RELEASE_ID,
    BF_RELEASE_ID,
    OBJECT_TYPE,
    OBJECT_ID,
    REVISION,
    OBJECT_NAME,
    DIFF_TYPE,
    TOROKUYMD, TOROKUHMS, TOROKUUSER,
    KOSINYMD,KOSINHMS, KOSINUSER
)
SELECT
    9999999999,
    ?,  /* 1, release_id */
    RR.OBJECT_TYPE,
    RR.OBJECT_ID,
    RR.REVISION,
    RR.OBJECT_NAME,
    RR.DIFF_TYPE,
    RR.TOROKUYMD,
    RR.TOROKUHMS,
    RR.TOROKUUSER,
    TO_CHAR(SYSDATE,'yyyymmdd'),
    TO_CHAR(SYSDATE,'hh24miss'),
    SYS_CONTEXT('USERENV','MODULE')
FROM
     MS_ERD_RELEASES RR
WHERE
    1 = 1
AND RR.OBJECT_TYPE    = 'TABLE'
AND RR.DIFF_TYPE      = 'S'