INSERT INTO RR_ERD_RELEASES
(
   AF_RELEASE_ID
  ,BF_RELEASE_ID
  ,OBJECT_TYPE
  ,OBJECT_ID
  ,REVISION
  ,OBJECT_NAME
  ,DIFF_TYPE
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
  ,BIKO
)
VALUES
(
   ? /* 1, AF_RELEASE_ID */
  ,? /* 2, BF_RELEASE_ID */
  ,? /* 3, OBJECT_TYPE */
  ,? /* 4, OBJECT_ID */
  ,? /* 5, REVISION */
  ,? /* 6, OBJECT_NAME */
  ,? /* 7, DIFF_TYPE */
  ,? /* 8, TOROKUYMD */
  ,? /* 9, TOROKUHMS */
  ,? /* 10, TOROKUUSER */
  ,? /* 11, KOSINYMD */
  ,? /* 12, KOSINHMS */
  ,? /* 13, KOSINUSER */
  ,? /* 14, BIKO */
)