INSERT INTO KR_TAB_DEF_REVISION
(
   TAB_DEF_ID
  ,TAB_DEF_REVISION
  ,TAB_DEF_NAME
  ,LAST_UPDATE_YMD
  ,LAST_UPDATE_HHMISS
  ,UPDATE_FLG
  ,NEW_FLG
  ,SVN_REVISION
  ,SVN_PATH
  ,EXISTS_FLG
  ,TRKM_STATUS
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ? /* 1, TAB_DEF_ID */
  ,? /* 2, TAB_DEF_REVISION */
  ,? /* 3, TAB_DEF_NAME */
  ,? /* 4, LAST_UPDATE_YMD */
  ,? /* 5, LAST_UPDATE_HHMISS */
  ,? /* 6, UPDATE_FLG */
  ,? /* 7, NEW_FLG */
  ,? /* 8, SVN_REVISION */
  ,? /* 9, SVN_PATH */
  ,? /* 10, EXISTS_FLG */
  ,? /* 11, TRKM_STATUS */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)