INSERT INTO MS_ERD_RELEASES
(
   RELEASE_ID
  ,OBJECT_TYPE
  ,OBJECT_ID
  ,REVISION
  ,OBJECT_NAME
  ,DIFF_TYPE
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ? /* 1, RELEASE_ID */
  ,? /* 2, OBJECT_TYPE */
  ,? /* 3, OBJECT_ID */
  ,? /* 4, REVISION */
  ,? /* 5, OBJECT_NAME */
  ,? /* 6, DIFF_TYPE */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)