INSERT INTO RR_TAB_DEF_INFO
(
   TAB_DEF_ID
  ,TAB_DEF_NAME
  ,TAB_DEF_REVISION_AF
  ,TAB_DEF_REVISION_BF
  ,SVN_REVISION
  ,AUTHOUR
  ,UPDATOR
  ,LOGICAL_TABLE_NAME
  ,PHYSICAL_TABLE_NAME
  ,TABLE_COMMENT
  ,COLUMN_ID
  ,LOGICAL_COLUMN_NAME
  ,PHYSICAL_COLUMN_NAME
  ,COLUMN_COMMENT
  ,DATA_TYPE
  ,DATA_LENGTH
  ,DATA_PRECISION
  ,DATA_SCALE
  ,PK_FLG
  ,NULLABLE
  ,DATA_DEFAULT
  ,TRKM_STATUS
  ,SEGOSEI_CHECK_STATUS
  ,SEGOSEI_CHECK_LOG_ID
  ,EXISTS_FLG
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ? /* 1, TAB_DEF_ID */
  ,? /* 2, TAB_DEF_NAME */
  ,? /* 3, TAB_DEF_REVISION_AF */
  ,? /* 4, TAB_DEF_REVISION_BF */
  ,? /* 5, SVN_REVISION */
  ,? /* 6, AUTHOUR */
  ,? /* 7, UPDATOR */
  ,? /* 8, LOGICAL_TABLE_NAME */
  ,? /* 9, PHYSICAL_TABLE_NAME */
  ,? /* 10, TABLE_COMMENT */
  ,? /* 11, COLUMN_ID */
  ,? /* 12, LOGICAL_COLUMN_NAME */
  ,? /* 13, PHYSICAL_COLUMN_NAME */
  ,? /* 14, COLUMN_COMMENT */
  ,? /* 15, DATA_TYPE */
  ,? /* 16, DATA_LENGTH */
  ,? /* 17, DATA_PRECISION */
  ,? /* 18, DATA_SCALE */
  ,? /* 19, PK_FLG */
  ,? /* 20, NULLABLE */
  ,? /* 21, DATA_DEFAULT */
  ,? /* 22, TRKM_STATUS */
  ,? /* 23, SEGOSEI_CHECK_STATUS */
  ,? /* 24, SEGOSEI_CHECK_LOG_ID */
  ,? /* 25, EXISTS_FLG */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)