INSERT INTO MS_IND_COLUMNS
(
   INDEX_NAME
  ,REVISION
  ,TABLE_ID
  ,COLUMN_ID
  ,COLUMN_NAME
  ,COLUMN_POSITION
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
  ,BIKO
)
VALUES
(
   ? /* 1, INDEX_NAME */
  ,? /* 2, REVISION */
  ,? /* 3, TABLE_ID */
  ,? /* 4, COLUMN_ID */
  ,? /* 5, COLUMN_NAME */
  ,? /* 6, COLUMN_POSITION */
  ,? /* 7, TOROKUYMD */
  ,? /* 8, TOROKUHMS */
  ,? /* 9, TOROKUUSER */
  ,? /* 10, KOSINYMD */
  ,? /* 11, KOSINHMS */
  ,? /* 12, KOSINUSER */
  ,? /* 13, BIKO */
)