INSERT INTO MS_TABLES
(
	 	TRKM_ID
	,	TAB_DEF_ID
	,	TABLE_ID
	,   SERVICE_NAME
    ,   SUBSYSTEM_NAME
	,	REVISION
	,	LOGICAL_TABLE_TAG
	,	LOGICAL_TABLE_NAME
	,	PHYSICAL_TABLE_NAME
	,	TRKM_STATUS
	,	TABLE_COMMENT
	,	SEGOSEI_CHECK_STATUS
	,	TICKET_NUMBER
	,	EXISTS_FLG
	,	TOROKUYMD
	,	TOROKUHMS
	,	TOROKUUSER
	,	KOSINYMD
	,	KOSINHMS
	,	KOSINUSER
)
VALUES
(
	 ?	/* 1	TRKM_ID */
	,?	/* 2	TAB_DEF_ID */
	,?	/* 3	TABLE_ID */
	,?	/* 4	SERVICE_NAME */
	,?	/* 5	SUBSYSTEM_NAME */
	,?	/* 6	REVISION */
	,?	/* 7	LOGICAL_TABLE_TAG */
	,?	/* 8	LOGICAL_TABLE_NAME */
	,?	/* 9	PHYSICAL_TABLE_NAME */
	,?	/* 10	TRKM_STATUS */
	,?	/* 11	TABLE_COMMENT */
	,?	/* 12	SEGOSEI_CHECK_STATUS */
	,?	/* 13	TICKET_NUMBER */
	,?	/* 14	EXISTS_FLG */
    ,TO_CHAR(SYSDATE,'YYYYMMDD')
    ,TO_CHAR(SYSDATE,'HH24MISS')
    ,SYS_CONTEXT('USERENV','MODULE')
    ,TO_CHAR(SYSDATE,'YYYYMMDD')
    ,TO_CHAR(SYSDATE,'HH24MISS')
    ,SYS_CONTEXT('USERENV','MODULE')
)