INSERT INTO RR_TABLES
(
   TRKM_ID
  ,TAB_DEF_ID
  ,TABLE_ID
  ,REVISION_AF
  ,REVISION_BF
  ,LOGICAL_TABLE_TAG
  ,LOGICAL_TABLE_NAME
  ,PHYSICAL_TABLE_NAME
  ,TRKM_STATUS
  ,TABLE_COMMENT
  ,SEGOSEI_CHECK_STATUS
  ,TICKET_NUMBER
  ,EXISTS_FLG
)
VALUES
(
   ? /* 1, TRKM_ID */
  ,? /* 2, TAB_DEF_ID */
  ,? /* 3, TABLE_ID */
  ,? /* 4, REVISION_AF */
  ,? /* 5, REVISION_BF */
  ,? /* 6, LOGICAL_TABLE_TAG */
  ,? /* 7, LOGICAL_TABLE_NAME */
  ,? /* 8, PHYSICAL_TABLE_NAME */
  ,? /* 9, TRKM_STATUS */
  ,? /* 10, TABLE_COMMENT */
  ,? /* 11, SEGOSEI_CHECK_STATUS */
  ,? /* 12, TICKET_NUMBER */
  ,? /* 13, EXISTS_FLG */
)