INSERT INTO MS_TABLES
(
	 	TRKM_ID
	,	TAB_DEF_ID
	,	TABLE_ID
	,	REVISION
	,	LOGICAL_TABLE_TAG
	,	LOGICAL_TABLE_NAME
	,	PHYSICAL_TABLE_NAME
	,	TRKM_STATUS
	,	TABLE_COMMENT
	,	SEGOSEI_CHECK_STATUS
	,	TICKET_NUMBER
	,	EXISTS_FLG
)
VALUES
(
	 ?	/* 1	TRKM_ID */
	,?	/* 2	TAB_DEF_ID */
	,?	/* 3	TABLE_ID */
	,?	/* 4	REVISION */
	,?	/* 5	LOGICAL_TABLE_TAG */
	,?	/* 6	LOGICAL_TABLE_NAME */
	,?	/* 7	PHYSICAL_TABLE_NAME */
	,?	/* 8	TRKM_STATUS */
	,?	/* 9	TABLE_COMMENT */
	,?	/* 10	SEGOSEI_CHECK_STATUS */
	,?	/* 11	TICKET_NUMBER */
	,?	/* 12	EXISTS_FLG */
)