MERGE INTO MS_INDEXES
USING DUAL
ON (
		MS_INDEXES.INDEX_NAME = ?	/* 1	INDEX_NAME */
	)
-- 既存レコードの更新
WHEN MATCHED THEN
	UPDATE SET
	 REVISION			=		?				/* 2	REVISION */
	,TABLE_ID			=		?				/* 3	TABLE_ID */
	,TAB_DEF_ID			=		?				/* 4	TAB_DEF_ID */
	,TICKET_NUMBER      =       ?               /* 5    TICKET_NUMBER */
	,UNIQUENESS			=		?				/* 6	UNIQUENESS */
	,FUNCTION			=		?				/* 7	FUNCTION */
	,BITMAP				=		?				/* 8	BITMAP */
	,REVERSE			=		?				/* 9	REVERSE */
	,KEY_COMPRESS		=		?				/* 10	KEY_COMPRESS */
	,COMMIT_FLG			=		?				/* 11	COMMIT_FLG */
	,FUNCTION_FOMULA	=		?				/* 12	FUNCTION_FOMULA */
	,LOCALITY			=		?				/* 13	LOCALITY */
	,PARTITIONED		=		?				/* 14	PARTITIONED */
	,STATUS				=		?				/* 15	STATUS */
	,PK_INDEX_FLG		=		?				/* 16	PK_INDEX_FLG */
	,KOSINYMD			=		TO_CHAR(SYSDATE,'YYYYMMDD')
	,KOSINHMS			=		TO_CHAR(SYSDATE,'HH24MISS')
	,KOSINUSER			=		SYS_CONTEXT('USERENV','MODULE')
-- 新規レコードの作成
WHEN NOT MATCHED THEN
	INSERT (
		INDEX_NAME
	,	REVISION
	,	TABLE_ID
	,	TAB_DEF_ID
	,	UNIQUENESS
	,	FUNCTION
	,	BITMAP
	,	REVERSE
	,	KEY_COMPRESS
	,	COMMIT_FLG
	,	FUNCTION_FOMULA
	,	LOCALITY
	,	PARTITIONED
	,	STATUS
	,	PK_INDEX_FLG
	,   TICKET_NUMBER
	,	TOROKUYMD
	,	TOROKUHMS
	,	TOROKUUSER
	,	KOSINYMD
	,	KOSINHMS
	,	KOSINUSER
) VALUES (
	 ?	/* 17	INDEX_NAME */
	,?	/* 18	REVISION */
	,?	/* 19	TABLE_ID */
	,?	/* 20	TAB_DEF_ID */
	,?	/* 21	UNIQUENESS */
	,?	/* 22	FUNCTION */
	,?	/* 23	BITMAP */
	,?	/* 24	REVERSE */
	,?	/* 25	KEY_COMPRESS */
	,?	/* 26	COMMIT_FLG */
	,?	/* 27	FUNCTION_FOMULA */
	,?	/* 28	LOCALITY */
	,?	/* 29	PARTITIONED */
	,?	/* 30	STATUS */
	,?	/* 31	PK_INDEX_FLG */
    ,?  /* 32    TICKET_NUMBER */
    ,TO_CHAR(SYSDATE,'YYYYMMDD')
    ,TO_CHAR(SYSDATE,'HH24MISS')
    ,SYS_CONTEXT('USERENV','MODULE')
    ,TO_CHAR(SYSDATE,'YYYYMMDD')
    ,TO_CHAR(SYSDATE,'HH24MISS')
    ,SYS_CONTEXT('USERENV','MODULE')
)