MERGE INTO KR_TAB_DEF_REVISION
USING DUAL
ON (
	 KR_TAB_DEF_REVISION.TAB_DEF_NAME	= ?   /* 1, TAB_DEF_NAME */
	)
-- 既存レコードの更新
WHEN MATCHED THEN
	UPDATE SET
		 KR_TAB_DEF_REVISION.UPDATE_FLG = '1'
		,KR_TAB_DEF_REVISION.SVN_REVISION       = ? /* 2, SVN_REVISION */
		,KR_TAB_DEF_REVISION.LAST_UPDATE_YMD    = ? /* 3, LAST_UPDATE_YMD */
		,KR_TAB_DEF_REVISION.LAST_UPDATE_HHMISS = ? /* 4, LAST_UPDATE_HHMISS */
		,KR_TAB_DEF_REVISION.NEW_FLG = '0'
		,KR_TAB_DEF_REVISION.TRKM_STATUS = '9'
		,KR_TAB_DEF_REVISION.EXISTS_FLG = '1'
		,KR_TAB_DEF_REVISION.SVN_PATH = ?           /* 5, SVN_PATH */
		,KR_TAB_DEF_REVISION.TAB_DEF_REVISION = ?   /* 6, TAB_DEF_REVISION */
		,KR_TAB_DEF_REVISION.KOSINYMD = TO_CHAR(SYSDATE, 'YYYYMMDD')
		,KR_TAB_DEF_REVISION.KOSINHMS = TO_CHAR(SYSDATE, 'HH24MISS')
		,KR_TAB_DEF_REVISION.KOSINUSER = SYS_CONTEXT('USERENV','MODULE')
-- 新規レコードの作成
WHEN NOT MATCHED THEN
	INSERT (
			TAB_DEF_ID,
			TAB_DEF_REVISION,
			TAB_DEF_NAME,
			LAST_UPDATE_YMD,
			LAST_UPDATE_HHMISS,
			UPDATE_FLG,
			NEW_FLG,
			TRKM_STATUS,
			SVN_REVISION,
			SVN_PATH,
			EXISTS_FLG,
			TOROKUYMD,
			TOROKUHMS,
			TOROKUUSER,
			KOSINYMD,
			KOSINHMS,
			KOSINUSER
	) VALUES (
		?,  /* 7,  TAB_DEF_ID */
		?,  /* 8,  TAB_DEF_REVISION */
		?,  /* 9,  TAB_DEF_NAME */
		?,  /* 10,  LAST_UPDATE_YMD */
		?,  /* 11, LAST_UPDATE_HHMISS */
		'0',
		'1',
		'9',
		?,  /* 12, SVN_REVISION */
		?,  /* 13, SVN_PATH */
		'1',
		TO_CHAR(SYSDATE, 'YYYYMMDD'),
		TO_CHAR(SYSDATE, 'HH24MISS'),
		SYS_CONTEXT('USERENV','MODULE'),
		TO_CHAR(SYSDATE, 'YYYYMMDD'),
		TO_CHAR(SYSDATE, 'HH24MISS'),
		SYS_CONTEXT('USERENV','MODULE')
	)