MERGE INTO MS_TABLES
USING DUAL
ON (
		MS_TABLES.PHYSICAL_TABLE_NAME = ?	/* 1	PHYSICAL_TABLE_NAME */
	)
-- 既存レコードの更新
WHEN MATCHED THEN
	UPDATE SET
	 REVISION				=	?	/* 2	REVISION */
	,LOGICAL_TABLE_NAME		=	?	/* 3	LOGICAL_TABLE_NAME */
	,TRKM_STATUS			=	?	/* 4	TRKM_STATUS */
	,TABLE_COMMENT			=	?	/* 5	TABLE_COMMENT */
	,SEGOSEI_CHECK_STATUS	=	?	/* 6	SEGOSEI_CHECK_STATUS */
	,TICKET_NUMBER			=	?	/* 7	TICKET_NUMBER */
	,TRKM_ID                =   ?   /* 8    TRKM_ID       */
	,KOSINYMD			=		TO_CHAR(SYSDATE,'YYYYMMDD')
	,KOSINHMS			=		TO_CHAR(SYSDATE,'HH24MISS')
	,KOSINUSER			=		SYS_CONTEXT('USERENV','MODULE')
-- 新規レコードの作成
WHEN NOT MATCHED THEN
	INSERT (
		TRKM_ID
	,	TAB_DEF_ID
	,	TABLE_ID
	,   SERVICE_NAME
    ,   SUBSYSTEM_NAME
	,	REVISION
	,	LOGICAL_TABLE_NAME
	,	PHYSICAL_TABLE_NAME
	,	TRKM_STATUS
	,	TABLE_COMMENT
	,	SEGOSEI_CHECK_STATUS
	,	TICKET_NUMBER
	,	EXISTS_FLG
	,	TOROKUYMD
	,	TOROKUHMS
	,	TOROKUUSER
	,	KOSINYMD
	,	KOSINHMS
	,	KOSINUSER
) VALUES (
	 ?						/* 9	TRKM_ID */
	,?						/* 10	TAB_DEF_ID */
	,SQ_MS_TABLES.NEXTVAL	/*   	TABLE_ID */
	,?						/* 11   SERVICE_NAME */
	,?						/* 12   SUBSYSTEM_NAME */
	,?						/* 13   REVISION */
	,?						/* 14	LOGICAL_TABLE_NAME */
	,?						/* 15	PHYSICAL_TABLE_NAME */
	,?						/* 16	TRKM_STATUS */
	,?						/* 17	TABLE_COMMENT */
	,?						/* 18	SEGOSEI_CHECK_STATUS */
	,?						/* 19	TICKET_NUMBER */
	,?						/* 20	EXISTS_FLG */
    ,TO_CHAR(SYSDATE,'YYYYMMDD')
    ,TO_CHAR(SYSDATE,'HH24MISS')
    ,SYS_CONTEXT('USERENV','MODULE')
    ,TO_CHAR(SYSDATE,'YYYYMMDD')
    ,TO_CHAR(SYSDATE,'HH24MISS')
    ,SYS_CONTEXT('USERENV','MODULE')
)