MERGE INTO MS_TABLES
USING DUAL
ON (
		MS_TABLES.PHYSICAL_TABLE_NAME = ?	/* 1	PHYSICAL_TABLE_NAME */
	)
-- 既存レコードの更新
WHEN MATCHED THEN
	UPDATE SET
	 REVISION				=	?	/* 2	REVISION */
	,LOGICAL_TABLE_NAME		=	?	/* 3	LOGICAL_TABLE_NAME */
	,TRKM_STATUS			=	?	/* 4	TRKM_STATUS */
	,TABLE_COMMENT			=	?	/* 5	TABLE_COMMENT */
	,SEGOSEI_CHECK_STATUS	=	?	/* 6	SEGOSEI_CHECK_STATUS */
	,TICKET_NUMBER			=	?	/* 7	TICKET_NUMBER */
	,TRKM_ID                =   ?   /* 8    TRKM_ID       */
-- 新規レコードの作成
WHEN NOT MATCHED THEN
	INSERT (
		TRKM_ID
	,	TAB_DEF_ID
	,	TABLE_ID
	,	REVISION
	,	LOGICAL_TABLE_NAME
	,	PHYSICAL_TABLE_NAME
	,	TRKM_STATUS
	,	TABLE_COMMENT
	,	SEGOSEI_CHECK_STATUS
	,	TICKET_NUMBER
	,	EXISTS_FLG
) VALUES (
	 ?						/* 9	TRKM_ID */
	,?						/* 10	TAB_DEF_ID */
	,SQ_MS_TABLES.NEXTVAL	/*   	TABLE_ID */
	,?						/* 11   REVISION */
	,?						/* 12	LOGICAL_TABLE_NAME */
	,?						/* 13	PHYSICAL_TABLE_NAME */
	,?						/* 14	TRKM_STATUS */
	,?						/* 15	TABLE_COMMENT */
	,?						/* 16	SEGOSEI_CHECK_STATUS */
	,?						/* 17	TICKET_NUMBER */
	,?						/* 18	EXISTS_FLG */
)