SELECT
     TP.RELEASE_ID
    ,TAB.TICKET_NUMBER
    ,TAB.TABLE_ID              	AS OBJECT_ID
    ,TAB.REVISION               AS REVISION
    ,'TABLE'        			AS OBJECT_TYPE
    ,TAB.PHYSICAL_TABLE_NAME	AS OBJECT_NAME
    ,CASE WHEN REL.OBJECT_ID IS NULL THEN 'C' ELSE 'U' END AS DIFF_TYPE
FROM
     TP_TICKET_NUMBERS4RELEASE TP
    ,MS_TABLES TAB
    ,MS_ERD_RELEASES REL
WHERE
    TP.TICKET_NUMBER = TAB.TICKET_NUMBER
AND TP.RELEASE_ID 	 = ?
AND TAB.TABLE_ID     = REL.OBJECT_ID(+)
