SELECT
		TRKM_ID
	,	TAB_DEF_ID
	,	TABLE_ID
	,   SERVICE_NAME
    ,   SYSTEM_NAME
    ,   SUBSYSTEM_NAME
	,	REVISION
	,	LOGICAL_TABLE_TAG
	,	LOGICAL_TABLE_NAME
	,	PHYSICAL_TABLE_NAME
	,	TRKM_STATUS
	,	TABLE_COMMENT
	,	SEGOSEI_CHECK_STATUS
	,	TICKET_NUMBER
	,	EXISTS_FLG
FROM
    MS_TABLES
WHERE
    PHYSICAL_TABLE_NAME IN (tableNames)