SELECT
   TAB_DEF_ID
  ,TAB_DEF_REVISION
  ,TAB_DEF_NAME
  ,LAST_UPDATE_YMD
  ,LAST_UPDATE_HHMISS
  ,UPDATE_FLG
  ,NEW_FLG
  ,SVN_REVISION
  ,SVN_PATH
  ,EXISTS_FLG
  ,TRKM_STATUS
FROM
  KR_TAB_DEF_REVISION
WHERE
    1 = 1
AND TAB_DEF_NAME in (tabDefNames)