SELECT
		TBL.PHYSICAL_TABLE_NAME
	,	IND.INDEX_NAME
	,	IND.REVISION
	,	IND.TABLE_ID
	,	IND.TAB_DEF_ID
	,	IND.TICKET_NUMBER
	,	IND.UNIQUENESS
	,	IND.FUNCTION
	,	IND.BITMAP
	,	IND.REVERSE
	,	IND.KEY_COMPRESS
	,	IND.COMMIT_FLG
	,	IND.FUNCTION_FOMULA
	,	IND.LOCALITY
	,	IND.PARTITIONED
	,	IND.STATUS
	,	IND.PK_INDEX_FLG
FROM
	MS_INDEXES  IND,
    MS_TABLES   TBL
WHERE
    IND.TABLE_ID = TBL.TABLE_ID
AND INDEX_NAME IN (indexNames)
ORDER BY
	INDEX_NAME