UPDATE MS_ERD_RELEASES
SET
  RELEASE_ID   = ?         /* 1, RELEASE_ID */
  ,OBJECT_TYPE = ?         /* 2, OBJECT_TYPE */
  ,OBJECT_ID   = ?         /* 3, OBJECT_ID */
  ,REVISION    = ?         /* 4, REVISION */
  ,OBJECT_NAME = ?         /* 5, OBJECT_NAME */
  ,DIFF_TYPE   = ?         /* 6, DIFF_TYPE */
  ,KOSINYMD	    =	TO_CHAR(SYSDATE,'YYYYMMDD')
  ,KOSINHMS	    =	TO_CHAR(SYSDATE,'HH24MISS')
  ,KOSINUSER	=	SYS_CONTEXT('USERENV','MODULE')
WHERE
  OBJECT_NAME  = ?         /* 7, OBJECT_NAME */