UPDATE MS_IND_COLUMNS
SET
   INDEX_NAME = ?          /* 1, INDEX_NAME */
  ,REVISION = ?            /* 2, REVISION */
  ,TABLE_ID = ?            /* 3, TABLE_ID */
  ,COLUMN_ID = ?           /* 4, COLUMN_ID */
  ,COLUMN_NAME = ?         /* 5, COLUMN_NAME */
  ,COLUMN_POSITION = ?     /* 6, COLUMN_POSITION */
  ,KOSINYMD	    =	TO_CHAR(SYSDATE,'YYYYMMDD')
  ,KOSINHMS	    =	TO_CHAR(SYSDATE,'HH24MISS')
  ,KOSINUSER	=	SYS_CONTEXT('USERENV','MODULE')
WHERE
    INDEX_NAME      = ? /* 7, INDEX_NAME */
AND COLUMN_POSITION = ? /* 8, COLUMN_POSITION */