INSERT INTO TP_TICKET_NUMBERS4RELEASE
(
   RELEASE_ID
  ,TRKM_ID
  ,TICKET_NUMBER
)
VALUES
(
   ? /* 1, RELEASE_ID */
  ,? /* 2, TRKM_ID */
  ,? /* 3, TICKET_NUMBER */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)