INSERT INTO TP_TICKET_NUMBERS4RELEASE
(
   RELEASE_ID
  ,TRKM_ID
  ,TICKET_NUMBER
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
  ,BIKO
)
VALUES
(
   ? /* 1, RELEASE_ID */
  ,? /* 2, TRKM_ID */
  ,? /* 3, TICKET_NUMBER */
  ,? /* 4, TOROKUYMD */
  ,? /* 5, TOROKUHMS */
  ,? /* 6, TOROKUUSER */
  ,? /* 7, KOSINYMD */
  ,? /* 8, KOSINHMS */
  ,? /* 9, KOSINUSER */
  ,? /* 10, BIKO */
)