UPDATE TP_TICKET_NUMBERS4RELEASE
SET
   RELEASE_ID    = ?            /* 1, RELEASE_ID */
  ,TRKM_ID       = ?            /* 2, TRKM_ID */
  ,TICKET_NUMBER = ?            /* 3, TICKET_NUMBER */
  ,KOSINYMD	     = TO_CHAR(SYSDATE,'YYYYMMDD')
  ,KOSINHMS	     = TO_CHAR(SYSDATE,'HH24MISS')
  ,KOSINUSER	 = SYS_CONTEXT('USERENV','MODULE')
WHERE
    1 = 1
AND RELEASE_ID   = ?
AND TRKM_ID      = ?