CREATE TABLE MS_IND_COLUMNS (
	INDEX_NAME			VARCHAR2(30)	NOT NULL,
	REVISION			NUMBER(38,0)	NOT NULL,
	TABLE_ID			NUMBER(38,0)	NOT	NULL,
	COLUMN_ID			NUMBER(38,0)	NOT NULL, 
	COLUMN_NAME			VARCHAR2(30)	NOT	NULL,
	COLUMN_POSITION		NUMBER(38,0)	NOT NULL,
	TOROKUYMD			VARCHAR2(8),
	TOROKUHMS			VARCHAR2(6),
	TOROKUUSER			VARCHAR2(50),
	KOSINYMD			VARCHAR2(8),
	KOSINHMS			VARCHAR2(6),
	KOSINUSER			VARCHAR2(50),
	BIKO				VARCHAR2(250)
)
;

ALTER TABLE MS_IND_COLUMNS ADD CONSTRAINT PK_MS_IND_COLUMNS PRIMARY KEY (INDEX_NAME, TABLE_ID, COLUMN_POSITION)
;
