CREATE TABLE RR_ERD_RELEASES (
	AF_RELEASE_ID	NUMBER(38,0),
	BF_RELEASE_ID	NUMBER(38,0),
	OBJECT_TYPE		VARCHAR2(30),
	OBJECT_ID		NUMBER(38,0),
	REVISION		NUMBER(38,0),
	OBJECT_NAME		VARCHAR2(30),
	DIFF_TYPE		CHAR(1)		DEFAULT 'N'	NOT NULL,
	TOROKUYMD		VARCHAR2(8),
	TOROKUHMS		VARCHAR2(6),
	TOROKUUSER		VARCHAR2(50),
	KOSINYMD		VARCHAR2(8),
	KOSINHMS		VARCHAR2(6),
	KOSINUSER		VARCHAR2(50),
	BIKO			VARCHAR2(250)
)
; 

ALTER TABLE RR_ERD_RELEASES ADD CONSTRAINT PK_RR_ERD_RELEASES PRIMARY KEY(AF_RELEASE_ID, OBJECT_TYPE, OBJECT_ID)
;
