CREATE TABLE RR_INDEXES 
(	
	INDEX_NAME			VARCHAR2(30)	NOT NULL,
	REVISION_AF			NUMBER(38,0),
	REVISION_BF			NUMBER(38,0),
	TABLE_ID			NUMBER(38,0)	NOT NULL, 
	TAB_DEF_ID			NUMBER(38,0)	NOT NULL, 
	TICKET_NUMBER		NUMBER(38,0)	NOT NULL,
	UNIQUENESS			CHAR(1)			DEFAULT 'N', 
	FUNCTION			CHAR(1)			DEFAULT 'N', 
	BITMAP				CHAR(1)			DEFAULT 'N', 
	REVERSE				CHAR(1)			DEFAULT 'N', 
	KEY_COMPRESS		CHAR(1)			DEFAULT 'N', 
	COMMIT_FLG			CHAR(1)			DEFAULT '1', 
	FUNCTION_FOMULA		VARCHAR2(1024), 
	LOCALITY			CHAR(1)			DEFAULT 'N', 
	PARTITIONED			CHAR(1)			DEFAULT 'N', 
	STATUS				VARCHAR2(10)	DEFAULT 'VALID', 
	PK_INDEX_FLG		CHAR(1)			DEFAULT '0',
	TOROKUYMD			VARCHAR2(8),
	TOROKUHMS			VARCHAR2(6),
	TOROKUUSER			VARCHAR2(50),
	KOSINYMD			VARCHAR2(8),
	KOSINHMS			VARCHAR2(6),
	KOSINUSER			VARCHAR2(50),
	BIKO				VARCHAR2(250)
)
;

COMMENT ON TABLE RR_INDEXES IS '[DBA][000056]';

ALTER TABLE RR_INDEXES ADD CONSTRAINT PK_RR_INDEXES PRIMARY KEY (INDEX_NAME, REVISION_AF)
;