CREATE TABLE RR_TAB_COLUMNS
(
 	TAB_DEF_ID				NUMBER(38,0),
	TABLE_ID				NUMBER(38,0),
 	REVISION_AF				NUMBER(38,0),
 	REVISION_BF				NUMBER(38,0),
 	AUTHOUR					VARCHAR2(300),
 	UPDATOR					VARCHAR2(300),
	LOGICAL_TABLE_TAG		VARCHAR2(30),
	LOGICAL_TABLE_NAME		VARCHAR2(200)		NOT NULL,
	PHYSICAL_TABLE_NAME		VARCHAR2(30)		NOT NULL,
	TABLE_COMMENT			VARCHAR2(300),
 	COLUMN_ID				NUMBER(20,0),
	LOGICAL_COLUMN_TAG		VARCHAR2(30),
 	LOGICAL_COLUMN_NAME		VARCHAR2(300),
 	PHYSICAL_COLUMN_NAME	VARCHAR2(60),
	COLUMN_COMMENT			VARCHAR2(300),
 	DATA_TYPE				VARCHAR2(30),
 	DATA_LENGTH 			VARCHAR2(30),
	DATA_PRECISION			VARCHAR2(30),
	DATA_DEFAULT			VARCHAR2(30),
	DATA_SCALE				VARCHAR2(30),
 	PK_FLG					VARCHAR2(2),
	NULLABLE				CHAR(1),
	TRKM_STATUS				CHAR(1),
	SEGOSEI_CHECK_STATUS	CHAR(1),
	SEGOSEI_CHECK_LOG_ID	NUMBER(38,0),
	TICKET_NUMBER           NUMBER(38,0),
	EXISTS_FLG				CHAR(1)	default '0',
	TOROKUYMD				VARCHAR2(8),
	TOROKUHMS				VARCHAR2(6),
	TOROKUUSER				VARCHAR2(50),
	KOSINYMD				VARCHAR2(8),
	KOSINHMS				VARCHAR2(6),
	KOSINUSER				VARCHAR2(50),
	BIKO					VARCHAR2(250)
)
;

ALTER TABLE RR_TAB_COLUMNS ADD CONSTRAINT PK_RR_TAB_COLUMNS PRIMARY KEY
(TABLE_ID,REVISION_AF,COLUMN_ID,LOGICAL_COLUMN_NAME)
;

CREATE INDEX IX01_RR_TAB_COLUMNS ON RR_TAB_COLUMNS KEY (TABLE_ID,REVISION_AF)
;