CREATE TABLE RR_TABLES (
	TRKM_ID					NUMBER(38,0)		NOT NULL,
	TAB_DEF_ID				NUMBER(38,0)		NOT NULL,
	TABLE_ID				NUMBER(38,0)		NOT NULL,
	REVISION_AF				NUMBER(38,0)		NOT NULL,
	REVISION_BF				NUMBER(38,0)		NOT NULL,
	LOGICAL_TABLE_TAG		VARCHAR2(30),
	LOGICAL_TABLE_NAME		VARCHAR2(200)		NOT NULL,
	PHYSICAL_TABLE_NAME		VARCHAR2(30)		NOT NULL,
	TRKM_STATUS				CHAR(1),
	TABLE_COMMENT			VARCHAR2(300),
	SEGOSEI_CHECK_STATUS	CHAR(1),
    TICKET_NUMBER           NUMBER(38,0),
	EXISTS_FLG				CHAR(1) default '0'
)
;

ALTER TABLE RR_TABLES ADD CONSTRAINT PK_RR_TABLES PRIMARY KEY  (PHYSICAL_TABLE_NAME,REVISION_AF)
;
