CREATE TABLE  TR_ERD_TAB_COLUMNS (
	TRKM_ID					NUMBER(38,0),
	TABLE_ID				NUMBER(38,0),
	LOGICAL_TABLE_NAME		VARCHAR2(300),
	PHYSICAL_TABLE_NAME		VARCHAR2(30),
	TABLE_COMMENT			VARCHAR2(300),
	DICT_COLUMN_ID			NUMBER(38,0),
	COLUMN_ID				NUMBER(38,0),
	LOGICAL_COLUMN_NAME		VARCHAR2(200),
	PHYSICAL_COLUMN_NAME	VARCHAR2(30),
	COLUMN_COMMENT			VARCHAR2(300),
	DATA_TYPE				VARCHAR2(30),
	DATA_LENGTH				VARCHAR2(30),
	DATA_PRECISION			VARCHAR2(30),
	DATA_DEFAULT			VARCHAR2(30),
	NULLABLE				CHAR(1),
	PK_FLG					NUMBER(38,0),
	EXISTS_FLG				CHAR(1)	default '0',
    TOROKUYMD			    VARCHAR2(8),
    TOROKUHMS				VARCHAR2(6),
    TOROKUUSER				VARCHAR2(50),
    KOSINYMD				VARCHAR2(8),
    KOSINHMS				VARCHAR2(6),
    KOSINUSER				VARCHAR2(50),
    BIKO					VARCHAR2(250)
)
;

ALTER TABLE TR_ERD_TAB_COLUMNS ADD CONSTRAINT PK_TR_ERD_TAB_COLUMNS PRIMARY KEY
(TABLE_ID,DICT_COLUMN_ID,COLUMN_ID);