INSERT INTO TR_COMMIT_HISTORY
(
   REPOSITORY_KIND
  ,REPOSITORY_NAME
  ,ROOT_URL
  ,RIGHT_BASE_URL
  ,LEFT_BASE_URL
  ,REVISION
  ,COMMITTER
  ,COMMENTS
  ,ACTION
  ,PATH
  ,FILE_NAME
  ,COMMIT_YMD
  ,COMMIT_HMS
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
  ,BIKO
)
VALUES
(
   ? /* 1, REPOSITORY_KIND */
  ,? /* 2, REPOSITORY_NAME */
  ,? /* 3, ROOT_URL */
  ,? /* 4, RIGHT_BASE_URL */
  ,? /* 5, LEFT_BASE_URL */
  ,? /* 6, REVISION */
  ,? /* 7, COMMITTER */
  ,? /* 8, COMMENTS */
  ,? /* 9, ACTION */
  ,? /* 10, PATH */
  ,? /* 11, FILE_NAME */
  ,? /* 12, COMMIT_YMD */
  ,? /* 13, COMMIT_HMS */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)