INSERT INTO RS_SQL_TABLES_EXP
(
   HEAD_REVISION
  ,PROJECT_NAME
  ,FILE_NAME
  ,PATH
  ,SUB_LINE
  ,TABLE_NAME
  ,TABLE_ALIAS
  ,CALL_TYPE
  ,CRUD_TYPE
  ,DEPTH
  ,REVISION
  ,AUTHOR
  ,COMMIT_YMD
  ,COMMIT_HMS
  ,EXTENSION
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ? /* 1, HEAD_REVISION */
  ,? /* 2, PROJECT_NAME */
  ,? /* 3, FILE_NAME */
  ,? /* 4, PATH */
  ,? /* 5, SUB_LINE */
  ,? /* 6, TABLE_NAME */
  ,? /* 7, TABLE_ALIAS */
  ,? /* 8, CALL_TYPE */
  ,? /* 9, CRUD_TYPE */
  ,? /* 10, DEPTH */
  ,? /* 11, REVISION */
  ,? /* 12, AUTHOR */
  ,? /* 13, COMMIT_YMD */
  ,? /* 14, COMMIT_HMS */
  ,? /* 15, EXTENSION */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)