INSERT INTO RS_SUBJECTID_XQLPATH_IDX
(
   SUBJECT_ID
  ,PATH
  ,REVISION
  ,COMMITER
  ,UPDATE_FLG
  ,NEW_FLG
  ,FILE_NAME
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ? /* 1, SUBJECT_ID */
  ,? /* 2, PATH */
  ,? /* 3, REVISION */
  ,? /* 4, COMMITER */
  ,? /* 5, UPDATE_FLG */
  ,? /* 6, NEW_FLG */
  ,? /* 7, FILE_NAME */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)