INSERT INTO KR_NASA_TABLE_SEQ
(
   TABLE_NAME
  ,CURRENT_ID
  ,PREVIOUS_ID
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ? /* 1, TABLE_NAME */
  ,? /* 2, CURRENT_ID */
  ,? /* 3, PREVIOUS_ID */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)