MERGE INTO V_CHANGESETS TGT
USING (
    SELECT
        WK.REVISION,
        WK.COMMITTER,
        WK.COMMENTS,
        WK.ACTION,
        WK.PATH,
        WK.FILE_NAME,
        WK.COMMIT_DATE,
        WK.COMMIT_HMS
    FROM
        WK_CHANGE_SETS WK
) SRC
  ON (
    TGT.REVISION = SRC.REVISION
  )
-- 新規レコードの作成
WHEN NOT MATCHED THEN
INSERT (
   REVISION
  ,COMMITTER
  ,COMMENTS
  ,ACTION
  ,PATH
  ,FILE_NAME
  ,COMMIT_DATE
  ,COMMIT_HMS
)
VALUES
(
   SRC.REVISION
  ,SRC.COMMITTER
  ,SRC.COMMENTS
  ,SRC.ACTION
  ,SRC.PATH
  ,SRC.FILE_NAME
  ,SRC.COMMIT_DATE
  ,SRC.COMMIT_HMS
)