MERGE INTO RS_SVN_SRC_INFO
USING DUAL
  ON (
    RS_SVN_SRC_INFO.PATH = ?    /* 1, PATH */
  )
-- 既存レコードの更新
WHEN MATCHED THEN
UPDATE SET
   HEAD_REVISION    = ?     /* 2, HEAD_REVISION */
  ,PROJECT_NAME     = ?     /* 3, PROJECT_NAME */
  ,FILE_NAME        = ?     /* 4, FILE_NAME */
  ,REVISION         = ?     /* 5, REVISION */
  ,AUTHOR           = ?     /* 6, AUTHOR */
  ,COMMIT_YMD       = ?     /* 7, COMMIT_YMD */
  ,COMMIT_HMS       = ?     /* 8, COMMIT_HMS */
  ,EXTENSION        = ?     /* 9, EXTENSION */
  ,KOSINYMD         = TO_CHAR(SYSDATE,'YYYYMMDD')
  ,KOSINHMS         = TO_CHAR(SYSDATE,'HH24MISS')
  ,KOSINUSER        = SYS_CONTEXT('USERENV','MODULE')
-- 新規レコードの作成
WHEN NOT MATCHED THEN
INSERT (
   HEAD_REVISION
  ,PROJECT_NAME
  ,FILE_NAME
  ,PATH
  ,REVISION
  ,AUTHOR
  ,COMMIT_YMD
  ,COMMIT_HMS
  ,EXTENSION
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ?  /* 10, HEAD_REVISION */
  ,?  /* 11, PROJECT_NAME */
  ,?  /* 12, FILE_NAME */
  ,?  /* 13, PATH */
  ,?  /* 14, REVISION */
  ,?  /* 15, AUTHOR */
  ,?  /* 16, COMMIT_YMD */
  ,?  /* 17, COMMIT_HMS */
  ,?  /* 18, EXTENSION */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)