SELECT
   REPOSITORY_KIND
  ,REPOSITORY_NAME
  ,ROOT_URL
  ,RIGHT_BASE_URL
  ,LEFT_BASE_URL
  ,REVISION
  ,COMMITTER
  ,COMMENTS
  ,ACTION
  ,PATH
  ,FILE_NAME
  ,COMMIT_YMD
  ,COMMIT_HMS
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
  ,BIKO
FROM
  TR_COMMIT_HISTORY
WHERE
    1 = 1
AND REPOSITORY_NAME = ?
AND ROOT_URL        = ?
AND RIGHT_BASE_URL  = ?
AND LEFT_BASE_URL   = ?
AND PATH            = ?