UPDATE RS_SUBJECTID_BLPATH_IDX
SET
   SUBJECT_GROUP_ID = ? /* 1, SUBJECT_GROUP_ID */
  ,SUBJECT_ID = ?       /* 2, SUBJECT_ID */
  ,PATH = ?             /* 3, PATH */
  ,REVISION = ?         /* 4, REVISION */
  ,UPDATE_FLG = ?       /* 5, UPDATE_FLG */
  ,NEW_FLG = ?          /* 6, NEW_FLG */
  ,FILE_NAME = ?        /* 7, FILE_NAME */
  ,KOSINYMD	    =	    TO_CHAR(SYSDATE,'YYYYMMDD')
  ,KOSINHMS	    =	    TO_CHAR(SYSDATE,'HH24MISS')
  ,KOSINUSER	=	    SYS_CONTEXT('USERENV','MODULE')
WHERE
    PATH = ?
AND SUBJECT_ID = ?