UPDATE TR_COMMIT_HISTORY
SET
   CHECKSUM_LEFT     = ?            /* 1, CHECKSUM_LEFT */
  ,CHECKSUM_RIGHT    = ?            /* 2, CHECKSUM_RIGHT */
  ,KOSINYMD	    =	 TO_CHAR(SYSDATE,'YYYYMMDD')
  ,KOSINHMS	    =	 TO_CHAR(SYSDATE,'HH24MISS')
  ,KOSINUSER	=	 SYS_CONTEXT('USERENV','MODULE')
WHERE
    1 = 1
AND replace(PATH, LEFT_BASE_URL) = ?  /* 3, PATH            */