CREATE TABLE KR_OBJECT_DEPENDENCIES (
	DEPENDENT_GRP_CD		CHAR(2),
	DEPENDENT_CD			CHAR(3),
	REFFERED_OWNER			VARCHAR2(30),
	OBJECT_OWNER			VARCHAR2(30),
	BACKUP_OWNER			VARCHAR2(30),
	IF_FLG					CHAR(1) DEFAULT '0',
	MASTER_DATA_CHECK_FLG	CHAR(1) DEFAULT '0',
	TOROKUYMD				VARCHAR2(8),
	TOROKUHMS				VARCHAR2(6),
	TOROKUUSER				VARCHAR2(50),
	KOSINYMD				VARCHAR2(8),
	KOSINHMS				VARCHAR2(6),
	KOSINUSER				VARCHAR2(50),
	BIKO					VARCHAR2(250)
)
;

ALTER TABLE KR_OBJECT_DEPENDENCIES ADD CONSTRAINT PK_KR_OBJECT_DEPENDENCIES PRIMARY KEY  (DEPENDENT_GRP_CD,DEPENDENT_CD)
;