CREATE TABLE KR_RELEASE_DIFFS (
    TAG_NAME            VARCHAR2(300),
	FROM_REVISION		NUMBER(38,0),
	TO_REVISION			NUMBER(38,0),
	HEADER_FLG			CHAR(1) DEFAULT '0' NOT NULL,
	TARGET_ENV_NAME     VARCHAR2(300),
	TOROKUYMD			CHAR(8),
	TOROKUHMS			VARCHAR2(6),
	TOROKUUSER			VARCHAR2(50),
	KOSINYMD			VARCHAR2(8),
	KOSINHMS			VARCHAR2(6),
	KOSINUSER			VARCHAR2(50)
)
; 

ALTER TABLE KR_RELEASE_DIFFS ADD CONSTRAINT PK_KR_RELEASE_DIFFS PRIMARY KEY(TAG_NAME,TO_REVISION);