INSERT INTO KR_OBJECT_DEPENDENCIES
(
   DEPENDENT_GRP_CD
  ,DEPENDENT_CD
  ,REFFERED_OWNER
  ,OBJECT_OWNER
  ,BACKUP_OWNER
  ,IF_FLG
  ,MASTER_DATA_CHECK_FLG
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
  ,BIKO
)
VALUES
(
   ? /* 1, DEPENDENT_GRP_CD */
  ,? /* 2, DEPENDENT_CD */
  ,? /* 3, REFFERED_OWNER */
  ,? /* 4, OBJECT_OWNER */
  ,? /* 5, BACKUP_OWNER */
  ,? /* 6, IF_FLG */
  ,? /* 7, MASTER_DATA_CHECK_FLG */
  ,? /* 8, TOROKUYMD */
  ,? /* 9, TOROKUHMS */
  ,? /* 10, TOROKUUSER */
  ,? /* 11, KOSINYMD */
  ,? /* 12, KOSINHMS */
  ,? /* 13, KOSINUSER */
  ,? /* 14, BIKO */
)