INSERT INTO KR_OBJECT_DEPENDENCIES
(
   DEPENDENT_GRP_CD
  ,DEPENDENT_CD
  ,REFFERED_OWNER
  ,OBJECT_OWNER
  ,BACKUP_OWNER
  ,IF_FLG
  ,MASTER_DATA_CHECK_FLG
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
)
VALUES
(
   ? /* 1, DEPENDENT_GRP_CD */
  ,? /* 2, DEPENDENT_CD */
  ,? /* 3, REFFERED_OWNER */
  ,? /* 4, OBJECT_OWNER */
  ,? /* 5, BACKUP_OWNER */
  ,? /* 6, IF_FLG */
  ,? /* 7, MASTER_DATA_CHECK_FLG */
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
  ,TO_CHAR(SYSDATE,'YYYYMMDD')
  ,TO_CHAR(SYSDATE,'HH24MISS')
  ,SYS_CONTEXT('USERENV','MODULE')
)