SELECT
   DEPENDENT_GRP_CD
  ,DEPENDENT_CD
  ,REFFERED_OWNER
  ,OBJECT_OWNER
  ,BACKUP_OWNER
  ,IF_FLG
  ,MASTER_DATA_CHECK_FLG
  ,TOROKUYMD
  ,TOROKUHMS
  ,TOROKUUSER
  ,KOSINYMD
  ,KOSINHMS
  ,KOSINUSER
  ,BIKO
FROM
  KR_OBJECT_DEPENDENCIES
WHERE
    1 = 1
AND DEPENDENT_GRP_CD = ?
AND DEPENDENT_CD     = ?