UPDATE KR_OBJECT_DEPENDENCIES
SET
   DEPENDENT_GRP_CD = ?        /* 1, DEPENDENT_GRP_CD */
  ,DEPENDENT_CD = ?            /* 2, DEPENDENT_CD */
  ,REFFERED_OWNER = ?          /* 3, REFFERED_OWNER */
  ,OBJECT_OWNER = ?            /* 4, OBJECT_OWNER */
  ,BACKUP_OWNER = ?            /* 5, BACKUP_OWNER */
  ,IF_FLG = ?                  /* 6, IF_FLG */
  ,MASTER_DATA_CHECK_FLG = ?   /* 7, MASTER_DATA_CHECK_FLG */
  ,KOSINYMD	    =	 TO_CHAR(SYSDATE,'YYYYMMDD')
  ,KOSINHMS	    =	 TO_CHAR(SYSDATE,'HH24MISS')
  ,KOSINUSER	=	 SYS_CONTEXT('USERENV','MODULE')
WHERE
    1 = 1
AND DEPENDENT_GRP_CD = ?
AND DEPENDENT_CD     = ?