CREATE TABLE RS_SUBJECTID_BLPATH_IDX (
	SUBJECT_GROUP_ID		VARCHAR2(500),
	SUBJECT_ID				VARCHAR2(500),
	PATH					VARCHAR2(500),
	REVISION				NUMBER(38,0),
	UPDATE_FLG				CHAR(1)	DEFAULT '0' NOT NULL,
	NEW_FLG					CHAR(1)	DEFAULT '0' NOT NULL,
	FILE_NAME				VARCHAR2(500),
	TOROKUYMD				VARCHAR2(8),
	TOROKUHMS				VARCHAR2(6),
	TOROKUUSER				VARCHAR2(50),
	KOSINYMD				VARCHAR2(8),
	KOSINHMS				VARCHAR2(6),
	KOSINUSER				VARCHAR2(50),
	BIKO					VARCHAR2(250)
)
;

ALTER TABLE RS_SUBJECTID_BLPATH_IDX ADD CONSTRAINT PK_RS_SUBJECTID_BLPATH_IDX PRIMARY KEY  (SUBJECT_GROUP_ID,SUBJECT_ID,PATH)
;
